name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: Build, Pack & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build solution and generate NuGet package
        run: dotnet pack src/Oceyra.Core.Generator.Tests.Helper/Oceyra.Core.Generator.Tests.Helper.csproj --configuration Release --output out  

      - name: Push generated package to Gitea registry
        run: dotnet nuget push ./out/*.nupkg --source ${{ secrets.nuget_api_url }} --skip-duplicate --no-symbols --api-key ${{ secrets.nuget_api_key }}
