name: publish to nuget
on:
  workflow_dispatch:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
    paths:
      - '**.cs*'

env:
  path_to_project: src/Oceyra.Core.Generator.Tests.Helper/Oceyra.Core.Generator.Tests.Helper.csproj

jobs:
  publish:
    name: Build, Pack & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Build solution and generate NuGet package
        run: dotnet pack $path_to_project -p:Version=0.2.${{ github.run_number }} --configuration Release --output bin  

      - name: Push generated package to Local registry
        if: ${{ vars.nuget_api_url != '' }}
        run: dotnet nuget push bin/*.nupkg --source ${{ vars.nuget_api_url }} --skip-duplicate --no-symbols --api-key ${{ secrets.nuget_api_key }} --version-suffix Beta

      - name: Push generated package to Nuget registry
        if: ${{ vars.nuget_api_url == '' }}
        run: dotnet nuget push bin/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols --api-key ${{ secrets.nuget_api_key }}
